<a href="https://colab.research.google.com/github/abrahul/Machine_Learning_Python/blob/main/Pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


In [15]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [16]:
t1.dtype

torch.float32

In [17]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [33]:
#Matrix
t3=torch.tensor([[1,2],[3,4],[5,6]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [20]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [21]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [22]:
print(t3)
t3.shape

tensor([[1, 2],
        [3, 4]])


torch.Size([2, 2])

In [23]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [24]:
# Matrix
#Note that it's not possible to create tensors with an improper shape.
t5 = torch.tensor([[5., 6, 11], 
                   [7, 8], 
                   [9, 10]])
t5

ValueError: ignored

In [25]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [26]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [27]:
# Compute derivatives
y.backward()

In [28]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [29]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [34]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [42, 42],
        [42, 42],
        [42, 42]])

In [35]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589, -0.2794],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [36]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [37]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [39]:
# Convert the numpy array to a torch tensor.
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [40]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [41]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])