<a href="https://colab.research.google.com/github/abrahul/Machine_Learning_Python/blob/main/Pytorch/Linear_Regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1

yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [66]:
# Weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(1,2,requires_grad=True)

In [67]:
print(w)
print(b)

tensor([[-1.3279, -0.8933,  0.1433],
        [-0.7172,  0.9146,  2.5073]], requires_grad=True)
tensor([[2.8264, 0.9615]], requires_grad=True)


In [68]:
def model(x):
  return x@w.t()+b

In [69]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-147.7998,  117.6949],
        [-187.4520,  176.6442],
        [-224.0904,  206.5414],
        [-165.7311,   59.9010],
        [-164.5240,  214.7838]], grad_fn=<AddBackward0>)


In [70]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [71]:
#MSE Loss
def mse(t1,t2):
  diff=t1-t2
  loss=torch.sum(diff*diff)/diff.numel()
  return loss

In [72]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(36122.8125, grad_fn=<DivBackward0>)


In [73]:
# Compute gradients
loss.backward()

In [74]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.3279, -0.8933,  0.1433],
        [-0.7172,  0.9146,  2.5073]], requires_grad=True)
tensor([[-21352.6250, -23401.4453, -14303.2598],
        [  5141.6870,   5977.3574,   3741.9431]])


In [91]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5

tensor([[-1.1144, -0.6593,  0.2863],
        [-0.7686,  0.8548,  2.4699]], requires_grad=True) tensor([[0., 0.]], requires_grad=True)


In [87]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(36122.8125, grad_fn=<DivBackward0>)


In [88]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0.]])


**Generate predictions

Calculate the loss

Compute gradients w.r.t the weights and biases

Adjust the weights by subtracting a small quantity proportional to the gradient

Reset the gradients to zero**

In [108]:
# Generate predictions
preds=model(inputs)
print(preds)

tensor([[ -82.0932,   99.8173],
        [-100.2022,  153.4047],
        [-120.2456,  179.0971],
        [-100.5571,   42.3519],
        [ -80.8686,  192.3022]], grad_fn=<AddBackward0>)


In [109]:
# Calculate the loss
loss=mse(preds,targets)
print(loss)

tensor(16913.2441, grad_fn=<DivBackward0>)


In [110]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)


tensor([[-29028.9297, -32071.3125, -19526.6426],
        [  6623.8750,   8021.4131,   5055.5410]])
tensor([[-518.9800,  124.1839]])


In [112]:
# Adjust weights & reset gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()


In [113]:
print(w)
print(b)

tensor([[-0.3565,  0.1771,  0.7958],
        [-0.9421,  0.6459,  2.3383]], requires_grad=True)
tensor([[ 0.0125, -0.0030]], requires_grad=True)


In [114]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1593.6604, grad_fn=<DivBackward0>)


In [128]:
# Train for 100 epochs
for i in range(100):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [129]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(29.8872, grad_fn=<DivBackward0>)


In [130]:
# Predictions
preds

tensor([[ 57.0706,  69.6332],
        [ 83.4069, 105.9206],
        [116.1159, 122.1040],
        [ 20.6483,  33.6662],
        [104.2631, 130.2253]], grad_fn=<AddBackward0>)

In [131]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


**Linear regression using PyTorch built-ins**

In [153]:
import torch.nn as nn

In [133]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [134]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [135]:
from torch.utils.data import TensorDataset

We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [156]:

# Define dataset
train_ds=TensorDataset(inputs,targets)
train_ds[0:4]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.]]))

DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [157]:
from torch.utils.data import DataLoader


In [160]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [161]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 68.,  97.,  70.],
        [103.,  43.,  36.],
        [ 91.,  87.,  65.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.]])
tensor([[102., 120.],
        [ 20.,  38.],
        [ 80., 102.],
        [103., 119.],
        [119., 133.]])


In each iteration, the data loader returns one batch of data with the given batch size. If `shuffle` is set to `True`, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

In [141]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2013,  0.3390, -0.1937],
        [ 0.3499, -0.2922, -0.0446]], requires_grad=True)
Parameter containing:
tensor([0.4772, 0.2248], requires_grad=True)


In [142]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2013,  0.3390, -0.1937],
         [ 0.3499, -0.2922, -0.0446]], requires_grad=True),
 Parameter containing:
 tensor([0.4772, 0.2248], requires_grad=True)]

In [143]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 29.5511,   4.2656],
        [ 36.2241,   3.4891],
        [ 52.1748, -11.0856],
        [ 28.4147,  21.6926],
        [ 33.3456,  -6.8132],
        [ 29.4134,   4.9077],
        [ 35.6914,   3.7367],
        [ 52.1823, -10.7803],
        [ 28.5524,  21.0506],
        [ 32.9506,  -7.2076],
        [ 29.0184,   4.5132],
        [ 36.0864,   4.1312],
        [ 52.7075, -11.3332],
        [ 28.8097,  22.0871],
        [ 33.4834,  -7.4553]], grad_fn=<AddmmBackward>)

In [162]:
# Import nn.functional
import torch.nn.functional as F

In [163]:
# Define loss function
loss_fn = F.mse_loss

In [164]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(41.1968, grad_fn=<MseLossBackward>)


In [165]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [166]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [149]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 484.5985
Epoch [20/100], Loss: 144.4344
Epoch [30/100], Loss: 117.4056
Epoch [40/100], Loss: 323.9215
Epoch [50/100], Loss: 114.8483
Epoch [60/100], Loss: 75.1057
Epoch [70/100], Loss: 76.3965
Epoch [80/100], Loss: 93.9752
Epoch [90/100], Loss: 29.2422
Epoch [100/100], Loss: 54.7620


In [150]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.6585,  72.3489],
        [ 79.1936,  98.8257],
        [123.3202, 134.5343],
        [ 28.7555,  47.8047],
        [ 92.2814, 109.6293],
        [ 57.4980,  71.4576],
        [ 78.4071,  98.4693],
        [123.3045, 134.9534],
        [ 29.9161,  48.6961],
        [ 92.6554, 110.1642],
        [ 57.8720,  71.9925],
        [ 78.0331,  97.9344],
        [124.1067, 134.8908],
        [ 28.3815,  47.2699],
        [ 93.4420, 110.5207]], grad_fn=<AddmmBackward>)

In [151]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [152]:
model(torch.tensor([[75, 63, 44.]]))


tensor([[54.5852, 69.3763]], grad_fn=<AddmmBackward>)