<a href="https://colab.research.google.com/github/abrahul/Machine_Learning_Python/blob/main/Pytorch/Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSOR BASICS**

In [ ]:
import torch

In [ ]:
x=torch.empty(1)
y=torch.empty(3)
print("x=",x)
print("y=",y)

x= tensor([-1.1027e+37])
y= tensor([-1.1027e+37,  3.0840e-41,  0.0000e+00])


In [ ]:
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[-1.1028e+37,  3.0840e-41,  4.4842e-44],
        [ 0.0000e+00,         nan,  0.0000e+00]])
tensor([[[-1.1028e+37,  3.0840e-41,  5.0447e-44],
         [ 0.0000e+00,         nan,  6.4460e-44]],

        [[ 1.3235e-14,  1.8369e+28,  1.9433e-19],
         [ 3.3738e-12,  7.4086e+28,  6.9397e+22]]])


In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7322, 0.9439, 0.8903],
        [0.6677, 0.9512, 0.7483],
        [0.2375, 0.3656, 0.8558],
        [0.3224, 0.7803, 0.0738],
        [0.7813, 0.0265, 0.6275]])


In [ ]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x=torch.ones(5,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
print(x.size())

torch.Size([5, 2])


In [ ]:
x.dtype

torch.float32

In [ ]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [ ]:
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [ ]:

# This will tell pytorch that it will need to calculate the gradients for this tensor,later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

In [ ]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)

In [ ]:
x+y

tensor([[0.4867, 0.1315],
        [1.6165, 0.7796]])

In [ ]:
torch.add(x,y)

tensor([[0.4867, 0.1315],
        [1.6165, 0.7796]])

In [ ]:
#same way for sub,mul and div

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.3498, 0.8338, 0.1501],
        [0.7928, 0.2628, 0.3499],
        [0.2206, 0.5299, 0.9756],
        [0.5046, 0.9984, 0.8662],
        [0.8545, 0.0975, 0.7386]])
tensor([0.3498, 0.7928, 0.2206, 0.5046, 0.8545])
tensor([0.7928, 0.2628, 0.3499])
tensor(0.2628)


In [ ]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.2628434896469116


In [ ]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
a = torch.ones(5)
print(a)
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b)) 

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
# If the Tensor is on the CPU (not the GPU),both objects will share the same memory location, 
# so changing one  will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
# careful when modifying
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    #z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    #z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()